spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2-console
      enabled: true
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      platform: h2